ORS_API_KEY = "eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImE5YjlmMTkyZGMwNDQ2MDE5NzFlNjAwY2UzZjZlYjYyIiwiaCI6Im11cm11cjY0In0="
GOOGLE_MAPS_API_KEY = "AIzaSyC-zsPTO2Mr1n1I05FQ0SAaH-iDeFaIU8U"
